---
version: 3
dependencies:
  system: |
    git-core
    python3-pip
    mariadb-devel
    postgresql-devel
    unzip
    git-lfs
    krb5-devel
    krb5-workstation
    rsync
  ansible_core:
    package_pip: ansible-core>=2.10
  python: |
    pymysql
    psycopg2-binary
  galaxy: |
    ---
      collections:
      - community.general
      - community.docker
      - azure.azcollection
      - community.azure
      - microsoft.ad
      - containers.podman
      - ansible.netcommon    
      - cloud.common
      - community.hashi_vault
      - community.mongodb
      - community.mysql
      - community.network
      - community.vmware
      - community.windows
      - community.zabbix

additional_build_steps: 
  prepend_base: |
    RUN python3 -m pip install --upgrade pip ansible

additional_build_files:
  - src: library/luarocks.py
    dest: library/luarocks.py
  